version: '3.9'

services:
  servidor_a:
    build: ./servers
    container_name: servidor_a
    environment:
      - SERVER_ID=Servidor_A_80pct
    cpus: '0.8'

  servidor_b:
    build: ./servers
    container_name: servidor_b
    environment:
      - SERVER_ID=Servidor_B_20pct
    cpus: '0.2'

  load_balancer:
    build: ./load_balancer
    container_name: load_balancer
    environment:
      - SERVER_ID=Load_Balancer

  cliente:
    image: curlimages/curl:latest
    container_name: cliente_node
    entrypoint: ["/bin/sh", "-c", "sleep infinity"]
