version: '3.9'

services:
  switch_central:
    image: p4lang/behavioral-model:latest
    container_name: switch_central
    volumes:
      - ./switch:/etc/p4/bmv2
    cap_add:
      - NET_ADMIN
    command: >
      simple_switch --i 1@eth1 --i 2@eth2 --i 3@eth3 /etc/p4/bmv2/simple_switch.json

  servidor_a:
    build: ./servers
    container_name: servidor_a
    environment:
      - SERVER_ID=Servidor_A_80pct
    cpus: '0.8'

  servidor_b:
    build: ./servers
    container_name: servidor_b
    environment:
      - SERVER_ID=Servidor_B_20pct
    cpus: '0.2'

  cliente:
    image: curlimages/curl:latest
    container_name: cliente_node
    entrypoint: ["/bin/sh", "-c", "sleep infinity"]