worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    server {
        listen       80;
        server_name  localhost;

        # Página padrão do servidor (pode ser o seu index do projeto)
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        # CRUCIAL: Endpoint para o Agente de AR coletar métricas de rede
        # Referente ao Objetivo Específico 1 e Tabela 1 do projeto
        location /nginx_status {
            stub_status;
            allow all; # Em produção, você restringiria ao IP do switch/agente
        }

        # Páginas de erro
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
}
