worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    # Definição do grupo de servidores (Upstream)
    # Aqui aplicamos a assimetria de capacidade (80% vs 20%) citada no projeto
    upstream servidores_backend {
        # Algoritmo Round Robin com Pesos (Weights)
        # O Servidor A (21) recebe 4 vezes mais carga que o B (22)
        server 10.0.0.21:80 weight=4; 
        server 10.0.0.22:80 weight=1;
    }

    server {
        listen 80;
        server_name balanceador_baseline;

        location / {
            proxy_pass http://servidores_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            
            # Timeouts para evitar que o balanceador trave se um backend demorar
            proxy_connect_timeout 5s;
            proxy_read_timeout 10s;
        }

        # Status para monitoramento do próprio balanceador
        location /nginx_status {
            stub_status;
            allow all;
        }
    }
}
